Repository Blaybus-8Hz/BE, pull requests merged in 2025-02, with the labels that each got.

#7 infra: 깃허브 액션으로 CI/CD 자동화 및 도커 설정
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  src/main/resources/application.yml
Labels: infra, chore

#10 fix: exp int에서 long으로 변환 (#9)
  src/main/java/com/haertz/be/auth/usecase/processor/CookieProcessor.java
  src/main/java/com/haertz/be/common/jwt/JwtProvider.java
  src/main/java/com/haertz/be/common/jwt/properties/JwtProperties.java
Labels: fix

#15 feat: 카카오페이 결제 api 연동
  .gitignore
  gradlew
  src/main/java/com/haertz/be/payment/Repository/PaymentRepository.java
  src/main/java/com/haertz/be/payment/Service/KakaoPayService.java
  src/main/java/com/haertz/be/payment/Service/PaymentSaveService.java
  src/main/java/com/haertz/be/payment/controller/KakaopayController.java
  src/main/java/com/haertz/be/payment/dto/Amount.java
  src/main/java/com/haertz/be/payment/dto/BankTransferDto.java
  src/main/java/com/haertz/be/payment/dto/KakaoPayApproveDto.java
  src/main/java/com/haertz/be/payment/dto/KakaoPayApproveRequestDto.java
  src/main/java/com/haertz/be/payment/dto/KakaoPayDTO.java
  src/main/java/com/haertz/be/payment/dto/KakaoPayRequestDTO.java
  src/main/java/com/haertz/be/payment/dto/PaymentSaveDto.java
  src/main/java/com/haertz/be/payment/entity/Payment.java
  src/main/java/com/haertz/be/payment/entity/PaymentMethod.java
  src/main/java/com/haertz/be/payment/entity/PaymentStatus.java
  src/main/resources/application.yml
Labels: enhancement, feat

#17 feat: 유저 프로필 반환 api 구현
  src/main/java/com/haertz/be/auth/dto/response/UserProfileDto.java
  src/main/java/com/haertz/be/common/jwt/JwtProvider.java
  src/main/java/com/haertz/be/user/controller/UserController.java
  src/main/java/com/haertz/be/user/dto/UserProfileDto.java
  src/main/java/com/haertz/be/user/usecase/GetUserProfileUseCase.java
Labels: fix, feat

#19 feat: 계좌이체 api 구현
  src/main/java/com/haertz/be/payment/Repository/PaymentRepository.java
  src/main/java/com/haertz/be/payment/Service/BankTransferService.java
  src/main/java/com/haertz/be/payment/Service/KakaoPayService.java
  src/main/java/com/haertz/be/payment/Service/PaymentSaveService.java
  src/main/java/com/haertz/be/payment/controller/BankTransferController.java
  src/main/java/com/haertz/be/payment/dto/BankTransferDto.java
  src/main/java/com/haertz/be/payment/dto/BankTransferRequestDto.java
  src/main/java/com/haertz/be/payment/dto/KakaoPayApproveDto.java
  src/main/java/com/haertz/be/payment/exception/PaymentErrorCode.java
Labels: fix, enhancement, feat

#22 feat: 구글캘린더 API를 사용해 구글미팅 링크 생성기능 구현
  src/main/java/com/haertz/be/googlemeet/controller/GoogleMeetController.java
  src/main/java/com/haertz/be/googlemeet/dto/GoogleMeetDto.java
  src/main/java/com/haertz/be/googlemeet/dto/GoogleMeetRequestDto.java
  src/main/java/com/haertz/be/googlemeet/exception/GoogleMeetErrorCode.java
  src/main/java/com/haertz/be/googlemeet/service/GoogleMeetService.java
  src/main/java/com/haertz/be/payment/Service/BankTransferService.java
  src/main/java/com/haertz/be/payment/Service/KakaoPayService.java
Labels: docs, enhancement, feat, style

#27 feat: 결제 취소 기능 구현
  src/main/java/com/haertz/be/googlemeet/controller/GoogleMeetController.java
  src/main/java/com/haertz/be/payment/controller/BankTransferController.java
  src/main/java/com/haertz/be/payment/controller/KakaopayController.java
  src/main/java/com/haertz/be/payment/dto/BankTransferCancelDto.java
  src/main/java/com/haertz/be/payment/dto/BankTransferCancelRequestDto.java
  src/main/java/com/haertz/be/payment/dto/BankTransferDto.java
  src/main/java/com/haertz/be/payment/dto/BankTransferRequestDto.java
  src/main/java/com/haertz/be/payment/dto/KakaoPayApproveDto.java
  src/main/java/com/haertz/be/payment/dto/KakaoPayCancelDto.java
  src/main/java/com/haertz/be/payment/dto/KakaoPayCancelRequestDto.java
  src/main/java/com/haertz/be/payment/exception/PaymentErrorCode.java
  src/main/java/com/haertz/be/payment/repository/PaymentRepository.java
  src/main/java/com/haertz/be/payment/service/BankTransferService.java
  src/main/java/com/haertz/be/payment/service/KakaoPayService.java
  src/main/java/com/haertz/be/payment/service/PaymentSaveService.java
Labels: enhancement, feat

#28 feat: 헤어디자이너 예약 요청 API 구현
  src/main/java/com/haertz/be/auth/repository/UserRepository.java
  src/main/java/com/haertz/be/booking/adaptor/BookingAdaptor.java
  src/main/java/com/haertz/be/booking/adaptor/DesignerScheduleAdaptor.java
  src/main/java/com/haertz/be/booking/controller/BookingController.java
  src/main/java/com/haertz/be/booking/converter/BookingConverter.java
  src/main/java/com/haertz/be/booking/dto/request/BookingInfoRequest.java
  src/main/java/com/haertz/be/booking/dto/response/BookingResponse.java
  src/main/java/com/haertz/be/booking/entity/Booking.java
  src/main/java/com/haertz/be/booking/entity/BookingStatus.java
  src/main/java/com/haertz/be/booking/entity/DesignerSchedule.java
  src/main/java/com/haertz/be/booking/entity/MeetingType.java
  src/main/java/com/haertz/be/booking/exception/BookingErrorCode.java
  src/main/java/com/haertz/be/booking/repository/BookingRepository.java
  src/main/java/com/haertz/be/booking/repository/DesignerScheduleRepository.java
  src/main/java/com/haertz/be/booking/service/BookingDomainService.java
  src/main/java/com/haertz/be/booking/service/DesignerScheduleDomainService.java
  src/main/java/com/haertz/be/booking/usecase/BookUseCase.java
  src/main/java/com/haertz/be/common/constant/StaticValue.java
  src/main/java/com/haertz/be/common/jwt/JwtProvider.java
  src/main/java/com/haertz/be/designer/adaptor/DesignerAdaptor.java
  src/main/java/com/haertz/be/designer/entity/Designer.java
  src/main/java/com/haertz/be/designer/exception/DesignerErrorCode.java
  src/main/java/com/haertz/be/designer/repository/DesignerRepository.java
  src/main/java/com/haertz/be/payment/entity/PaymentStatus.java
  src/main/java/com/haertz/be/payment/exception/PaymentErrorCode.java
  src/main/java/com/haertz/be/user/usecase/GetUserProfileUseCase.java
  src/main/resources/application.yml
Labels: feat, chore

#32 feat: 디자이너 엔티티 필드 수정 및 디자이너미팅링크 엔티티 생성
  src/main/java/com/haertz/be/designer/entity/Designer.java
  src/main/java/com/haertz/be/designer/entity/DesignerMeetingLink.java
  src/main/java/com/haertz/be/designer/entity/MeetingMode.java
Labels: feat

#34 feat: 결제 완료 및 환불 완료 시 paymant status 값 업데이트
  src/main/java/com/haertz/be/payment/dto/BankTransferDto.java
  src/main/java/com/haertz/be/payment/dto/KakaoPayApproveDto.java
  src/main/java/com/haertz/be/payment/dto/KakaoPayCancelDto.java
  src/main/java/com/haertz/be/payment/repository/temp.java
  src/main/java/com/haertz/be/payment/service/BankTransferService.java
  src/main/java/com/haertz/be/payment/service/KakaoPayService.java
Labels: feat

#37 feat: 디자이너 스케줄 & 예약 테이블 결제 상태 관리 및 결제 실패 처리시 로직 구현
  src/main/java/com/haertz/be/booking/adaptor/BookingAdaptor.java
  src/main/java/com/haertz/be/booking/adaptor/DesignerScheduleAdaptor.java
  src/main/java/com/haertz/be/booking/converter/BookingConverter.java
  src/main/java/com/haertz/be/booking/dto/request/BookingInfoRequest.java
  src/main/java/com/haertz/be/booking/dto/request/PreBookingRequest.java
  src/main/java/com/haertz/be/booking/entity/Booking.java
  src/main/java/com/haertz/be/booking/entity/DesignerSchedule.java
  src/main/java/com/haertz/be/booking/repository/BookingRepository.java
  src/main/java/com/haertz/be/booking/repository/DesignerScheduleRepository.java
  src/main/java/com/haertz/be/booking/service/BookingDomainService.java
  src/main/java/com/haertz/be/booking/service/DesignerScheduleDomainService.java
  src/main/java/com/haertz/be/booking/usecase/BookUseCase.java
  src/main/java/com/haertz/be/payment/exception/PaymentErrorCode.java
Labels: feat, refactor

#42 feat: 디자이너 별 예약 가능 날짜 및 시간 반환 API 구현
  src/main/java/com/haertz/be/booking/adaptor/DesignerScheduleAdaptor.java
  src/main/java/com/haertz/be/booking/constant/AvailableTimeSlots.java
  src/main/java/com/haertz/be/booking/controller/BookingController.java
  src/main/java/com/haertz/be/booking/exception/BookingErrorCode.java
  src/main/java/com/haertz/be/booking/repository/DesignerScheduleRepository.java
  src/main/java/com/haertz/be/booking/service/DesignerScheduleDomainService.java
  src/main/java/com/haertz/be/booking/usecase/GetAvailableDatesUseCase.java
  src/main/java/com/haertz/be/booking/usecase/GetAvailableTimesUseCase.java
  src/main/java/com/haertz/be/common/constant/StaticValue.java
Labels: feat

#43 feat: 유저, 예약, 디자이너스케줄, 결제 연결
  src/main/java/com/haertz/be/payment/dto/BankTransferDto.java
  src/main/java/com/haertz/be/payment/dto/BankTransferRequestDto.java
  src/main/java/com/haertz/be/payment/dto/KakaoPayApproveRequestDto.java
  src/main/java/com/haertz/be/payment/dto/KakaoPayCancelRequestDto.java
  src/main/java/com/haertz/be/payment/dto/KakaoPayDTO.java
  src/main/java/com/haertz/be/payment/dto/KakaoPayRequestDTO.java
  src/main/java/com/haertz/be/payment/dto/PaymentSaveDto.java
  src/main/java/com/haertz/be/payment/entity/Payment.java
  src/main/java/com/haertz/be/payment/service/BankTransferService.java
  src/main/java/com/haertz/be/payment/service/KakaoPayService.java
Labels: enhancement, feat

#52 feat : 디자이너 카테고리 별 조회 api 구현
  src/main/java/com/haertz/be/designer/controller/DesignerController.java
  src/main/java/com/haertz/be/designer/dto/response/DesignerResponse.java
  src/main/java/com/haertz/be/designer/entity/Specialty.java
  src/main/java/com/haertz/be/designer/repository/DesignerRepository.java
  src/main/java/com/haertz/be/designer/service/DesignerService.java
Labels: feat

#54 refactor: 디자이너 미팅 방식에 맞춘 예약 검증 기능 추가
  src/main/java/com/haertz/be/booking/entity/MeetingType.java
  src/main/java/com/haertz/be/booking/exception/BookingErrorCode.java
  src/main/java/com/haertz/be/booking/service/BookingDomainService.java
  src/main/java/com/haertz/be/booking/usecase/BookUseCase.java
  src/main/java/com/haertz/be/designer/entity/Designer.java
  src/main/java/com/haertz/be/designer/entity/MeetingMode.java
  src/main/java/com/haertz/be/designer/exception/DesignerErrorCode.java
Labels: style, refactor

#58 feat: 결제 취소 시 디자이너스케줄 테이블 삭제
  src/main/java/com/haertz/be/payment/controller/KakaopayController.java
  src/main/java/com/haertz/be/payment/dto/PayingCancelRequestDto.java
  src/main/java/com/haertz/be/payment/service/KakaoPayService.java
Labels: refactor

#69 feat: 예약내역 조회 문제 해결 및 디자이너 조회 API 분리
  src/main/java/com/haertz/be/designer/controller/DesignerController.java
  src/main/java/com/haertz/be/designer/repository/DesignerRepository.java
  src/main/java/com/haertz/be/designer/service/DesignerService.java
  src/main/java/com/haertz/be/designer/usecase/GetAllDesignersUseCase.java
  src/main/java/com/haertz/be/designer/usecase/GetFilteredDesignersUseCase.java
Labels: fix, feat

#71 feat: 디자이너 speciality 중복 선택 가능하도록 구현
  src/main/java/com/haertz/be/designer/controller/DesignerController.java
  src/main/java/com/haertz/be/designer/repository/DesignerRepository.java
  src/main/java/com/haertz/be/designer/service/DesignerService.java
  src/main/java/com/haertz/be/designer/usecase/GetFilteredDesignersUseCase.java
Labels: feat

#72 docs: 리드미 문서 업데이트
  README.md
Labels: docs
